### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED when using built-in serve-static with compression

### ISSUE THREAD

**Issue by GetThatCookie** [dimdenGD/ultimate-express#115]
Hi,

this is my whole first issue I'm reporting so plz don't be hard on me.
First of all I really like this project and currently switch our whole project to ultimate-express.

We use
- Nestjs
- compression alias shrink-ray-current (doesn't matter which one to use)
- express -> ultimate-express

So far everything seems good, but I'm having trouble using the built-in serve-static.
We don't pre-zip our static files, thats why we use compression for all routes including static.
If I use the built-in serve-static, the static files can not be served and prints the following error:

![Image](https://github.com/user-attachments/assets/5f79730c-40c9-4f60-9cfc-182c2912ba95)

As you can see not all files are broken, only a few are printing ERR_CONTENT_DECODING_FAILED.
If I use the express serve-static middleware, it works with no problem.

Maybe good to know but I don't know, I'm using Ubuntu Linux.
When I'm using Windows, the built-in doesn't work either, but the serve-static express middleware prints the error too, but only rare.

I thought about setting this here, but to be honest I don't know how to set it:
![Image](https://github.com/user-attachments/assets/52e34015-b97d-4015-8802-ba7b02a1c442)

I much appreciate any idea and help, thanks in advance!

**Comment by nigrosimone** [comment]
Strange that the ones that went wrong are all 1.1kB. Is this the actual size of the files?

**Comment by GetThatCookie** [comment]
No the compressed file size is between 600kB and 1,2MB and somewhere around 2-8MB uncompressed. If I look into the payload, there is nothing to show. With express serve-static everything works as expected... super strange...

**Comment by dimdenGD** [comment]
Could you make some minimal reproduction code?

**Comment by GetThatCookie** [comment]
Ok I will try in the next days. What I forgot to say, if I disable compression everything works, both serve-static and windows too, zero problems.

**Comment by GetThatCookie** [comment]
Got some time to debug and test again while trying to create some reproduction code... so far I can tell, that it's the "pipeStreamOverResponse" method. If I force the non ranged path, everything works as expected

![Image](https://github.com/user-attachments/assets/7e6f41ff-b544-4603-baec-a65aecd24a49)

**Comment by GetThatCookie** [comment]
Well actually it was quite easy to reproduce, sry for letting you wait and trying to debug myself haha

```
  const test = express();

  test.use(compression());

  test.use('/static', serveStatic('your_folder'));

  test.listen(3000, () => {
    console.log('Server is running on port 3000');
  });
```

**Comment by nigrosimone** [comment]
It is `static` from `ultimate-express` ?

```js
const express = require("ultimate-express");
const app = express();
app.use('/static',  express.static('your_folder'));
```

or from another library?

**Comment by GetThatCookie** [comment]
Sry my bad, yes it's exported from ultimate-express

```
import {static as serveStatic } from 'ultimate-express';
```

I forgot to switch to express.static in my example.

**Comment by nigrosimone** [comment]
Ok, I have found the problem, this is the reproducible script. 

It Happen only with large file (size > 768 * 1024) that are not served with workers but with `pipeStreamOverResponse()` (see https://github.com/dimdenGD/ultimate-express/blob/main/src/response.js#L744) . 

For the test I have used 24 MB json from https://github.com/json-iterator/test-data/blob/master/large-file.json

```js
const express = require("ultimate-express");
const compression = require("compression");
const path = require("path");

const app = express();

app.use(compression());
app.use('/static',  express.static(path.resolve(__dirname)));

app.listen(13333, () => {
  console.log("Server is running at http://localhost:13333");
});
```

http://localhost:13333/static/large-file.json

It seem send only the first chunk of the file

**Comment by nigrosimone** [comment]
I tried to fix it, but failed. It seems that `pipeStreamOverResponse` does not implement the case where the response should be compressed as it is done here https://github.com/dimdenGD/ultimate-express/blob/main/src/response.js#L144

we need someone better :D

**Comment by dimdenGD** [comment]
As a semi-fix, I can make it disable compression when sending large files. So they won't error anymore but won't be compressed either.

**Comment by GetThatCookie** [comment]
Well I can only agree partially. It's not good but also not bad practice, as always it depends. Especially "shrink-ray-current", it's like compression, but only for the first time. It compress fast at the first serve and recompress to maximum in the background for all other serves, which means all other requests comes directly from the LRU cache in the background - no CPU bottleneck.

I fully understand that there seems to be problems, that might be not fixable.

When using serve-static from express, it works with compression. Is there maybe a combination possible? So instead of disabling compression for the big files, maybe using express serve-static as a fallback?

**Comment by nigrosimone** [comment]
You are right. The problem is that "compress" monkey patches several methods that are from the native node http module which is different from the one Ultimate Express uses. Perhaps a solution could be developed a proper compression module, I don't know if @dimdenGD wants to add it in this project

**Comment by dimdenGD** [comment]
Good news: I managed to rewrite file sender to use Response pipe and got rid of `pipeStreamOverResponse`, so now `compression` seems to be able to inject into it.

Bad news: It still doesn't work properly. I get `net::ERR_INVALID_CHUNKED_ENCODING` randomly on about every second response. Haven't figured out why is this happening yet.

**Comment by GetThatCookie** [comment]
Tomorrow at work I will try your fix and debug too, maybe I can give some Feedback. Thanks so much for your effort!

**Comment by dimdenGD** [comment]
I'm using Windows and Chrome to test. Also interestingly I wasn't able to reproduce it with Windows Node.js fetch for some reason

**Comment by GetThatCookie** [comment]
@dimdenGD after some testing I still don't get it. All I can say, I don't have any problems with Firefox on Windows with this setup, but all Chromium browsers produce the same output. For me it's no big deal, because our platform is deployed on debian based docker image, but my inner monk don't like such unanswered problems 😄

**Comment by nigrosimone** [comment]
Maybe Chrome support a encoding that Firefox doesn't support and this One cause the problem?

Eg. Brotli or zstd

**Comment by GetThatCookie** [comment]
But why only on Windows? I/We? only get errors with this setup:

Windows -> Chromium -> compression

I also get errors on routes without serve-static, so for me the initial problem is fixed.

**Comment by nigrosimone** [comment]
I'm on Windows 11 with NodeJS v22.13.0

**Firefox**
_Request_:  `Accept-Encoding: gzip, deflate, br, zstd`
_Response_:  `content-encoding: br`

**Chrome**
_Request_:  `accept-encoding: gzip, deflate, br, zstd`
_Response_: `content-encoding: br`


Firefox works, Chrome ERR_CONTENT_DECODING_FAILED

same compression _br_ (Brotli)

Very strange

**Comment by dimdenGD** [comment]
Seems that when using `compression`, it starts using chunked transfer encoding (since length is not known), and this causes a huge amount of `write`s being used with 4-16KB chunks, which uWS seems to not like. When I throttle the writes, file always sends without errors

**Comment by GetThatCookie** [comment]
Can you elaborate what you mean by "throttle the writes" so I can test myself? Smaller files, changes in compression, uexpress, uws or stream settings?

**Comment by dimdenGD** [comment]
Just adding setTimeout before uws write in `_write`. Way too slow and inefficient to be an actual solution though

**Comment by nigrosimone** [comment]
I don't know if this can help solve this problem.

I have wasted a bit of time to resolve this issue, no solution found, but I want share  a new discovery.

If I debugging the code, always works, because debugging slowdown the "response write" like `setTimeout`

I have put some "console log" into the compression library

![Image](https://github.com/user-attachments/assets/70b61671-3c69-449b-84cb-7953b6f4270f)

When works, the `end` event on the `stream` is emitted

```
Server is running at http://localhost:13333
stream data 16384
stream data 2290
stream data 14094
stream data 16384
stream data 755
stream data 15629
stream data 16384
stream data 9963
stream data 6421
stream data 16384
stream data 11083
end
```

When doesn't works the `end` event on the `stream` is not emitted
```
Server is running at http://localhost:13333
stream data 16384
stream data 2290
stream data 14094
```

also note that there are far fewer chunks sent.

**Comment by nigrosimone** [comment]
Guys... maybe fixed, by I need a code review from @dimdenGD https://github.com/dimdenGD/ultimate-express/pull/149

I'm not confident is a good solution

**Comment by dimdenGD** [comment]
Published on NPM
